name: 'elib_dbt'
version: '1.0.0'
config-version: 2

profile: 'elib_profile'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  elib_dbt:
    staging:
      +schema: staging
      +materialized: view
    mart:
      +schema: mart
      +materialized: table
